# Generated by Django 5.0.1 on 2024-02-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pict',
            new_name='profileimg',
        ),
    ]
