# Generated by Django 5.0.1 on 2024-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
