# Generated by Django 5.0.1 on 2024-02-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_image',
        ),
    ]
