# Generated by Django 5.0.1 on 2024-02-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='bg.png', upload_to='post_images'),
        ),
    ]
